/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6;

/**
 *
 * @author Jared
 */
public class gui extends javax.swing.JFrame {

    /**
     * Creates new form gui
     */
    
    private student protectedStudent;
    private gradStudent protectedGrad;
    
    public gui() {
        
        student protectedStudent;
        gradStudent protectedGrad;
        
        initComponents();
        underGradButton.setSelected(true);
        attendedHogTrueButton.setSelected(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        underGradButton = new javax.swing.JRadioButton();
        gradButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        firstNameText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        middleInitText = new javax.swing.JTextField();
        lastNameText = new javax.swing.JTextField();
        address1Text = new javax.swing.JTextField();
        address2Text = new javax.swing.JTextField();
        cityText = new javax.swing.JTextField();
        stateText = new javax.swing.JTextField();
        zipText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ageText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        birthDateText = new javax.swing.JTextField();
        majorComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        favClassCombo = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        attendedHogTrueButton = new javax.swing.JRadioButton();
        attendedHogFalseButton = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        gradDateText = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        advisorFirstNameText = new javax.swing.JTextField();
        advisorLastNameText = new javax.swing.JTextField();
        thesisText = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        restoreButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        countryText = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        PUIDText = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        underGradButton.setText("Undergrad Student");
        underGradButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                underGradButtonActionPerformed(evt);
            }
        });

        gradButton.setText("Graduate Student");
        gradButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("First Name");

        jLabel2.setText("Middle Initial");

        jLabel3.setText("Last Name");

        jLabel4.setText("Address 1");

        jLabel5.setText("Address 2");

        jLabel6.setText("City");

        jLabel7.setText("State");

        jLabel8.setText("Zip code");

        address2Text.setPreferredSize(new java.awt.Dimension(122, 20));

        jLabel9.setText("Age");

        ageText.setPreferredSize(new java.awt.Dimension(122, 20));

        jLabel10.setText("Birth Date");

        majorComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CIT", "Physics", "Math", "Plant Science", "7 Year Plan" }));

        jLabel11.setText("Major");

        jLabel12.setText("Favorite Class");

        favClassCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CIT 155", "CIT 255", "Literature of Monty Python", "Presidency of Kanye West", "Jazz flue", "Theory of killer drones", "no comment" }));

        jLabel13.setText("Attended Hogwarts");

        attendedHogTrueButton.setText("true");
        attendedHogTrueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendedHogTrueButtonActionPerformed(evt);
            }
        });

        attendedHogFalseButton.setText("False");
        attendedHogFalseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendedHogFalseButtonActionPerformed(evt);
            }
        });

        jLabel14.setText("Graduation Date");

        gradDateText.setPreferredSize(new java.awt.Dimension(122, 20));

        jLabel15.setText("Advisor First Name");

        jLabel16.setText("Advisor Last Name");

        jLabel17.setText("Thesis Title");

        advisorLastNameText.setPreferredSize(new java.awt.Dimension(122, 20));

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        restoreButton.setText("Restore");
        restoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoreButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        jLabel18.setText("Country");

        countryText.setMinimumSize(new java.awt.Dimension(122, 20));
        countryText.setPreferredSize(new java.awt.Dimension(122, 20));

        jLabel19.setText("PUID");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(underGradButton)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel18)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ageText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(birthDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addComponent(saveButton)
                        .addGap(52, 52, 52)
                        .addComponent(clearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(restoreButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(address2Text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(gradButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(firstNameText)
                                    .addComponent(middleInitText)
                                    .addComponent(lastNameText)
                                    .addComponent(address1Text)
                                    .addComponent(cityText)
                                    .addComponent(stateText)
                                    .addComponent(zipText))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel15)
                                            .addGap(18, 18, 18)
                                            .addComponent(advisorFirstNameText))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel13)
                                                .addComponent(jLabel14))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(gradDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(attendedHogTrueButton)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(attendedHogFalseButton)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(favClassCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(majorComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17)
                                            .addComponent(jLabel19))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(advisorLastNameText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(thesisText)
                                            .addComponent(PUIDText)))))
                            .addComponent(countryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(underGradButton)
                    .addComponent(gradButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(majorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(middleInitText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(favClassCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(attendedHogTrueButton)
                    .addComponent(attendedHogFalseButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(address1Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(gradDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(address2Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(advisorFirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(advisorLastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(stateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(thesisText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(zipText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(PUIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(countryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(saveButton)
                        .addComponent(restoreButton)
                        .addComponent(clearButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(ageText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(birthDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void underGradButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_underGradButtonActionPerformed
        if (gradButton.isSelected()){
            gradButton.setSelected(false);
        }                   
    }//GEN-LAST:event_underGradButtonActionPerformed

    private void gradButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradButtonActionPerformed
        if (underGradButton.isSelected()){
            underGradButton.setSelected(false);
        }
    }//GEN-LAST:event_gradButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        countryText.setText("");
        thesisText.setText("");
        advisorLastNameText.setText("");
        advisorFirstNameText.setText("");
        gradDateText.setText("");
        birthDateText.setText("");
        ageText.setText("");
        zipText.setText("");
        stateText.setText("");
        cityText.setText("");
        address2Text.setText("");
        address1Text.setText("");
        lastNameText.setText("");
        middleInitText.setText("");
        firstNameText.setText("");
        attendedHogTrueButton.setSelected(true);
        attendedHogFalseButton.setSelected(false);
        favClassCombo.setSelectedIndex(0);
        majorComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void attendedHogTrueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendedHogTrueButtonActionPerformed
        if (attendedHogFalseButton.isSelected()){
            attendedHogFalseButton.setSelected(false);
        }
    }//GEN-LAST:event_attendedHogTrueButtonActionPerformed

    private void attendedHogFalseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendedHogFalseButtonActionPerformed
        if (attendedHogTrueButton.isSelected()){
            attendedHogTrueButton.setSelected(false);
        }
    }//GEN-LAST:event_attendedHogFalseButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        
        if (underGradButton.isSelected()){
            
            Boolean attendHog = true;
            
            if (attendedHogTrueButton.isSelected()){
                attendHog = true;
            }
            if (attendedHogFalseButton.isSelected()){
                attendHog = false;
            }
            
            student student1 = new student(firstNameText.getText(), lastNameText.getText(), middleInitText.getText(), address1Text.getText(), address2Text.getText(), cityText.getText(), stateText.getText(), zipText.getText(), countryText.getText(), birthDateText.getText(), majorComboBox.getSelectedItem().toString(), favClassCombo.getSelectedItem().toString(), gradDateText.getText(), attendHog); 
            
            protectedStudent = student1;
            
            ageText.setText(protectedStudent.calculateBirthday());
            
        }
        
        if (gradButton.isSelected()){
            
            Boolean attendHog = true;
            
            if (attendedHogTrueButton.isSelected()){
                attendHog = true;
            }
            if (attendedHogFalseButton.isSelected()){
                attendHog = false;
            }
            
            gradStudent gradStudent1 = new gradStudent(firstNameText.getText(), lastNameText.getText(), middleInitText.getText(), address1Text.getText(), address2Text.getText(), cityText.getText(), stateText.getText(), zipText.getText(), countryText.getText(), birthDateText.getText(), majorComboBox.getSelectedItem().toString(), favClassCombo.getSelectedItem().toString(), gradDateText.getText(), attendHog, thesisText.getText(), advisorFirstNameText.getText(), advisorLastNameText.getText()); 
            
            protectedGrad = gradStudent1;
            
            ageText.setText(protectedGrad.calculateBirthday());
            
        }
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void restoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoreButtonActionPerformed
        
        if (underGradButton.isSelected()){
            
            countryText.setText(protectedStudent.address.getCountry());
            thesisText.setText("");
            advisorLastNameText.setText("");
            advisorFirstNameText.setText("");
            gradDateText.setText(protectedStudent.getGradDate());
            birthDateText.setText(protectedStudent.getBirthday());
            ageText.setText(protectedStudent.calculateBirthday());
            zipText.setText(protectedStudent.address.getZip());
            stateText.setText(protectedStudent.address.getState());
            cityText.setText(protectedStudent.address.getCity());
            address2Text.setText(protectedStudent.address.getStreet2());
            address1Text.setText(protectedStudent.address.getStreet1());
            lastNameText.setText(protectedStudent.name.getLast());
            middleInitText.setText(protectedStudent.name.getMiddle());
            firstNameText.setText(protectedStudent.name.getFirst());
            favClassCombo.setSelectedItem(protectedStudent.getFavoriteClass());
            majorComboBox.setSelectedItem(protectedStudent.getMajor());
            
            if (protectedStudent.getHogYN()){
                attendedHogTrueButton.setSelected(true);
                attendedHogFalseButton.setSelected(false);
            }
            else if (!protectedStudent.getHogYN()){
                attendedHogTrueButton.setSelected(false);
                attendedHogFalseButton.setSelected(true);
            }
            
        }
        
        if (gradButton.isSelected()){
            
            countryText.setText(protectedGrad.address.getCountry());
            thesisText.setText(protectedGrad.getThesis());
            advisorLastNameText.setText(protectedGrad.getAdvisorLastName());
            advisorFirstNameText.setText(protectedGrad.getAdvisorFirstName());
            gradDateText.setText(protectedGrad.getGradDate());
            birthDateText.setText(protectedGrad.getBirthday());
            ageText.setText(protectedGrad.calculateBirthday());
            zipText.setText(protectedGrad.address.getZip());
            stateText.setText(protectedGrad.address.getState());
            cityText.setText(protectedGrad.address.getCity());
            address2Text.setText(protectedGrad.address.getStreet2());
            address1Text.setText(protectedGrad.address.getStreet1());
            lastNameText.setText(protectedGrad.name.getLast());
            middleInitText.setText(protectedGrad.name.getMiddle());
            firstNameText.setText(protectedGrad.name.getFirst());
            majorComboBox.setSelectedItem(protectedGrad.getMajor());
            favClassCombo.setSelectedItem(protectedGrad.getFavoriteClass());
            
            if (protectedGrad.getHogYN()){
                attendedHogTrueButton.setSelected(true);
                attendedHogFalseButton.setSelected(false);
            }
            else if (!protectedGrad.getHogYN()){
                attendedHogTrueButton.setSelected(false);
                attendedHogFalseButton.setSelected(true);
            }
            
        }
        
        
    }//GEN-LAST:event_restoreButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PUIDText;
    private javax.swing.JTextField address1Text;
    private javax.swing.JTextField address2Text;
    private javax.swing.JTextField advisorFirstNameText;
    private javax.swing.JTextField advisorLastNameText;
    private javax.swing.JTextField ageText;
    private javax.swing.JRadioButton attendedHogFalseButton;
    private javax.swing.JRadioButton attendedHogTrueButton;
    private javax.swing.JTextField birthDateText;
    private javax.swing.JTextField cityText;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField countryText;
    private javax.swing.JComboBox<String> favClassCombo;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JRadioButton gradButton;
    private javax.swing.JTextField gradDateText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JComboBox<String> majorComboBox;
    private javax.swing.JTextField middleInitText;
    private javax.swing.JButton restoreButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField stateText;
    private javax.swing.JTextField thesisText;
    private javax.swing.JRadioButton underGradButton;
    private javax.swing.JTextField zipText;
    // End of variables declaration//GEN-END:variables
}
